# site settings
title: devblog
subtitle: by atripes
email: alex@vie.at
description: A blog to store ideas and present them
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://atripes.at" # the base hostname & protocol for your site
author: atripes

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
#500px_url:
#facebook_url:
#github_url:
#gitlab_url: https://gitlab.com/u/andrewbanchich
#googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
#instagram_url: https://instagram.com
#linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
#pinterest_url:
#slack_url:
#twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
